### ISSUE TITLE
Submit the fourth iteration

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#172]
_Feel free to edit this post to add task or because of any other reason you find reasonable._

---

@RjiukYagami 
- [x] Close your issues if you've got any left.
- [x] Close/request a code review/merge your pull requests if you've got any left.
- [x] Update [the summary][wiki4] with the description of you've done during this iteration.
- [x] Choose 2-3 issues you want to solve during the fifth iteration (#149) and assign yourself to those issues.

- [x] Update the [Use cases wiki page](https://github.com/0mp/io-touchpad/wiki/Documentation:-Use-cases).

---

@piotrekp1 
- [x] Close your issues if you've got any left.
- [x] Close/request a code review/merge your pull requests if you've got any left.
- [x] Update [the summary][wiki4] with the description of you've done during this iteration.
- [x] Choose 2-3 issues you want to solve during the fifth iteration (#149) and assign yourself to those issues.

---

@michal7352 
- [x] Close your issues if you've got any left.
- [x] Close/request a code review/merge your pull requests if you've got any left.
- [x] Update [the summary][wiki4] with the description of you've done during this iteration.
- [x] Choose 2-3 issues you want to solve during the fifth iteration (#149) and assign yourself to those issues.

---

@0mp
- [x] Close your issues if you've got any left.
- [x] Close/request a code review/merge your pull requests if you've got any left.
- [x] Update [the summary][wiki4] with the description of you've done during this iteration.
- [x] Choose 2-3 issues you want to solve during the fifth iteration (#149) and assign yourself to those issues.

[wiki4]: https://github.com/0mp/io-touchpad/wiki/Summary:-v0.4%E2%80%90beta-(The-fourth-iteration)
